#debugging parameters#
PRINT_FUNCTION_TRACE=False
PRINT_DEBUG_LEVEL=0
#output settings
SAMPLE_DB_FILENAME= '""'
HOST_SAMPLING_ON=True
OUTPUT_HOSTS=True
OUTPUT_GENES=False # Set to false to save space
OUTPUT_STRAINS=False # Set to false to save space
HOST_SAMPLING_PERIOD=90.0
HOST_SAMPLE_SIZE=150
T_YEAR=360.0
T_BURNIN=10*360
T_END=100*360
PRINT_INFO_PERIOD=HOST_SAMPLING_PERIOD

#verification settings
VERIFICATION_ON=False
VERIFICATION_PERIOD=10800

#checkpoint settings
LOAD_FROM_CHECKPOINT=False
CHECKPOINT_LOAD_FILENAME='"RdivRunInterventionRegionalNoChangeOneTypeGene_2_s0_cp.sqlite"'
SAVE_TO_CHECKPOINT=True
CHECKPOINT_SAVE_FILENAME= '""'
CHECKPOINT_SAVE_PERIOD=T_END

#model parameters
SELECTION_MODE='SPECIFIC_IMMUNITY'
#random seed needs to be set to a fixed value if wants to replicate exactly the same realization
RANDOM_SEED= 942440369
N_GENES_INITIAL= 5000
N_GENES_PER_STRAIN= 40
N_LOCI= 2
N_ALLELES_INITIAL=N_LOCI*[1000]

#var groups settings
GROUPS_DO_NOT_SHARE_ALLELE = True
GROUP_GENE_RATIOS = [0,1] 
FIX_GENE_RATIO = True
TRADE_OFF_S = 0
CONTINUOUS_FUNCTION=False
FUNCTION_CATEGORY = [1,1]
MINIMUM_FUNCTION=0.025

#evolution settings
RECOMBINATION_ON=True #whether recombination is allowed
ECTOPIC_RECOMBINATION_RATE=[4.24e-04]
SIMILARITY_BIAS_RECOMBINATION = False
P_ECTOPIC_RECOMBINATION_IS_CONVERSION=0
RHO=0.8
EXPECTED_EQUILIBRIUM=100*360
# 0 is uniform_dist, 1 is categorical, 2 is that recomb is according their group id
RECOMB_UNIFORM_DIST=0
MUTATION_RATE=1.42e-08

#infection and immunity settings
UPSGROUP_DIFF_RECEPTOR=False
HIGH_FUNCTION_EXPRESS_FIRST=False ###in this implementation, we do not have high function
TRANSITION_RATE_NOT_IMMUNE=1.0 / 6.0 # switching rate. every 6 days
TRANSITION_RATE_IMMUNE=1000
IMMUNITY_LOSS_RATE=0.001
T_LIVER_STAGE=14.0

#generalized immunity settings
N_INFECTIONS_FOR_GENERAL_IMMUNITY=245
GENERAL_IMMUNITY_PARAMS=[51.4043638136979,284.518878105621,-0.0016944082357847,0.277409542527348]
CLEARANCE_RATE_IMMUNE=0.00511272898496179

#host settings
MEAN_HOST_LIFETIME=30.0 * T_YEAR
MAX_HOST_LIFETIME=80.0 * T_YEAR
N_POPULATIONS=1
N_HOSTS=[10000]
N_INITIAL_INFECTIONS=[20]
DISTANCE_MAT=[[1]]
DIST_POWER=1

#transmission settings 
BITING_RATE_MEAN=[0.06]
GENE_TRANSMISSIBILITY=1
COINFECTION_REDUCES_TRANSMISSION=True
BITING_RATE_RELATIVE_AMPLITUDE=[0.8]
BITING_RATE_PEAK_PHASE=[0.5]
DAILY_BITING_RATE_DISTRIBUTION=[]
IRS_ON=False
IRS_START_TIMES=[28800]
BITING_RATE_FACTORS=[[0.3]]
IRS_IMMIGRATION_RATE_FACTORS=[1]
RATE_FACTOR_SCALE = 1800
MDA_ON=False
MDA_START_TIMES=[250,300]
HOST_FAIL_RATE=[0.2,0.2] # percent of hosts that did not take the drug
DRUG_EFF_DURATION=[15,15] # How long the drug remains effective in the body
MDA_IMMIGRATION_RATE_FACTORS=[0.2,0.6]
IMMIGRATION_ON=True
IMMIGRATION_RATE=[1.0]
P_IMMIGRATION_INCLUDES_NEW_GENES=0
N_IMMIGRATION_NEW_GENES=0
REGION_TO_LOCAL_POP_SIZE_RATIO=1
